name: DIY_assistant
type: gradio-space
sdk: gradio

metadata:
  space_id: Chris4K/DIY_assistant
  original_url: https://huggingface.co/spaces/Chris4K/DIY_assistant

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"
